'use client';

import { motion } from 'framer-motion';
import { 
  Brain,
  Target,
  Sparkles,
  FileText,
  Building,
  ArrowRight
} from 'lucide-react';

interface LandingPageProps {
  onGetStarted: () => void;
}

export default function LandingPage({ onGetStarted }: LandingPageProps) {
  const features = [
    {
      icon: <Brain className="w-6 h-6 text-[#fcba28]" />,
      title: 'AI-Powered Questions',
      description: 'Get personalized interview questions generated by advanced AI technology'
    },
    {
      icon: <Target className="w-6 h-6 text-[#fcba28]" />,
      title: 'Role-Specific',
      description: 'Questions tailored to your target job role and experience level'
    },
    {
      icon: <Building className="w-6 h-6 text-[#fcba28]" />,
      title: 'Company-Focused',
      description: 'Questions aligned with your target company\'s culture and requirements'
    },
    {
      icon: <FileText className="w-6 h-6 text-[#fcba28]" />,
      title: 'Resume Analysis',
      description: 'Upload your resume for even more personalized questions'
    },
    {
      icon: <Sparkles className="w-6 h-6 text-[#fcba28]" />,
      title: 'Suggested Answers',
      description: 'Get detailed answer guidelines for each question'
    }
  ];

  return (
    <div className="min-h-screen bg-background text-white pt-20 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-6xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-[#fcba28] to-[#fcd978]"
          >
            AI Interview Generator
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-xl text-white/60 mb-8 max-w-2xl mx-auto"
          >
            Generate personalized interview questions based on your profile, target role, and company. Practice with AI-powered feedback to ace your next interview.
          </motion.p>
          <motion.button
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            onClick={onGetStarted}
            className="bg-gradient-to-r from-[#fcba28] to-[#fcd978] hover:from-[#fcd978] hover:to-[#fcba28] text-black font-semibold py-4 px-8 rounded-xl transition-all duration-300 flex items-center mx-auto group"
          >
            Get Started
            <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
          </motion.button>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 * (index + 3) }}
              className="bg-white/5 rounded-2xl p-6 hover:bg-white/10 transition-all duration-300"
            >
              <div className="bg-white/5 rounded-xl p-3 w-fit mb-4">
                {feature.icon}
              </div>
              <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-white/60">{feature.description}</p>
            </motion.div>
          ))}
        </div>

        {/* How It Works */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl font-bold mb-8">How It Works</h2>
          <div className="flex flex-col md:flex-row justify-center items-center gap-8">
            <div className="flex-1 max-w-xs">
              <div className="text-4xl font-bold text-[#fcba28] mb-4">1</div>
              <h3 className="text-xl font-semibold mb-2">Enter Your Details</h3>
              <p className="text-white/60">Provide information about your target role and company</p>
            </div>
            <div className="flex-1 max-w-xs">
              <div className="text-4xl font-bold text-[#fcba28] mb-4">2</div>
              <h3 className="text-xl font-semibold mb-2">Upload Resume</h3>
              <p className="text-white/60">Optionally upload your resume for personalized questions</p>
            </div>
            <div className="flex-1 max-w-xs">
              <div className="text-4xl font-bold text-[#fcba28] mb-4">3</div>
              <h3 className="text-xl font-semibold mb-2">Get Questions</h3>
              <p className="text-white/60">Receive tailored questions and suggested answers</p>
            </div>
          </div>
        </motion.div>

        {/* Call to Action */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl font-bold mb-4">Ready to Ace Your Interview?</h2>
          <p className="text-white/60 mb-8">Start generating personalized interview questions now</p>
          <button
            onClick={onGetStarted}
            className="bg-gradient-to-r from-[#fcba28] to-[#fcd978] hover:from-[#fcd978] hover:to-[#fcba28] text-black font-semibold py-4 px-8 rounded-xl transition-all duration-300 flex items-center mx-auto group"
          >
            Get Started
            <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
          </button>
        </motion.div>
      </div>
    </div>
  );
}
